name: wallet_crypto
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  mockito: ^5.4.4
  chopper: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.11
  riverpod_lint: ^2.3.7

flutter:


  uses-material-design: true
